FROM node:18-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
# We force install here because local install failed
RUN npm install
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]
