# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  AIR:
    sh: echo "$(go env GOPATH)/bin/air"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  dev:
    cmds:
      - "{{.AIR}}"